language: go
go:
- '1.6'
before_install:
- curl -o gpm https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm
- chmod +x "./gpm"
- "./gpm"
before_deploy:
- "./cross-compile.sh"
- mkdir -p deploy/go-meshblu-connector-dependency-manager/latest deploy/go-meshblu-connector-dependency-manager/$TRAVIS_TAG
- cp tmp/cross/* deploy/go-meshblu-connector-dependency-manager/latest
- cp tmp/cross/* deploy/go-meshblu-connector-dependency-manager/$TRAVIS_TAG
deploy:
  provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "i/CeKADZmW+zOJSz5YgoDpCN2KLdTlX69/jaRWdOO8fkkcUIc5b0HAOf+Nbu9hGfMqgVjies+wBn3S9AU1vjx/pdPC1yh1a2WYPR29HbnAjiTg3SfM04jaOp6Yua6akC5/8D34CqwLoT+7KkLroiIgPBTH8DJhD9hvGWRibAt7sKybI6B0Pr6QrmWpf2q8C1rUNYaM1wJUCRypNafKoxmt9qqkB2yanAVUGE751xpsHVpSMD2EjKUJ9yiu+TCP1u7tS3qlwNiOvsUxuJlJBSPvn+i1gw2N05gcmnfC9cXFMwayRvftiMCZjbH1znMbBYvb52bmzchwOzfZ/tq9QVYy2OE4oMLsYpqoYF/RON8cZv2sYAfT3+bNVojb4ykPzg6pIYSw/qtWITFaZnBqow9Erlb7c6M1mRmoz0tXZSbzITcHLpMN3sGvJTY3LuNiiRl+5jnVjg/bBZxM5iDhPOU+OfdHVyA8RY5X0jXe9z459OboP80VYxbE+sX3AVTeHFfnV9QmD4uTylr6+IGyHgWxAVWHaWzoikh0YoOrNDWlR4IMZDLJTr/MVbsXSCTkZg85FAknprqYpcEtj4tnU/Uy5h2zSK0LUFCyXU+KNHSetJ3VogfXIOmfst/LFjxZ4ryhlhJnqlys8fTZ+t24QXKomeldPcWNH4A5oZn2EEpjM="
  bucket: meshblu-connector
  region: us-west-2
  skip_cleanup: true
  local-dir: deploy
  detect_encoding: true
  upload-dir: tools
  on:
    tags: true
    repo: octoblu/go-meshblu-connector-dependency-manager
